apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pov
  description: An initial group for use during the Proof of Value phase, showcasing the functionality.
  links:
    - title: Backstage specification for the group kind
      url: https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-group
      
spec:
  type: root
  children: []